#Compiler
CC = g++

#Compiler flags

FILES = Simulate.cpp LoadConfig.cpp Random.cpp CreateEvent.cpp CreateProcess.cpp EventHandlers.cpp WriteLog.cpp Stats.cpp

OUTPUT = Simulate

all: $(OUTPUT)

$(OUTPUT): $(FILES)
	$(CC) $(FILES) -o $(OUTPUT)